theme: jekyll-theme-slate
title: Yun-Chen Lo
description: NTHU EE Master Student seeks breakthrough of technology through HW/SW co-design
logo: /pics/homepage_pic.jpg
# Google Analytics
google_analytics: UA-165000458-1